version: "2.1"
services:

  postgrest:
    image: postgrest/postgrest:latest
    ports:
      - "3000"
    depends_on:
      - postgresql
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}

  postgresql:
    build: ./postgresql/
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
